### ISSUE TITLE
Set temporary display

### ISSUE THREAD

**Issue by mishoboss** [EliasStar/DashD#7]
**Description**
Expose another http endpoint for temporary displaying a URL for given amount of seconds and then it goes back to the previously displayed URL.

**Possible Solutions**
Expose endpoint `/display_temporary` with get params `url` and 'duration'. The `duration` param gets integer value specifying the duration of seconds. After these number of seconds are passed, it loads the previously loaded URL, the one before the `/display_temporary` request occurred.

**Additional Context**
This feature would be very useful in cases like:
- Show a camera feed on doorbell ring.
- Show CCTV perimeter cameras on security alarm trigger.

After some time passes, displays return to their previously displayed page.

**Comment by EliasStar** [comment]
Such higher level logic should be implemented with a smart home "hub" (e.g. OpenHub or Home Assistant) or a seperate control server. DashD should be regarded as a lightweight wrapper between the hardware and a http enabled smart home server. Because of that all http endpoint are idempotent as DashD it self has no internal state.
